XMOJ.user.js

Added colors to the ACM ranking

Add rating

---

XMOJ.user.js

rename "rating" in the settings page

---

XMOJ.user.js

Make Cheaters Blue named

---

Server/Source/Initial.sql
Server/Source/Process.ts

[BUG] 时间错误：Invalid Date

---

Server/Source/Initial.sql

[BUG] 将数据库中TIMESTAMP类型转换为INTEAGER类型

---

XMOJ.user.js

[Feature Request] 在短消息界面添加用户名颜色

---

XMOJ.user.js

[Feature Reques] 发布讨论快捷键

---

Server/Source/Initial.sql
Server/Source/Process.ts
XMOJ.user.js

[Feature request] 提醒应当有单独的数据表，而不是将讨论提及和短消息提醒分开

---

XMOJ.user.js

[Feature Request] 加载增加动画

---

XMOJ.user.js

[Bug] 讨论列表中最后回复时间错误

---

Update.json
XMOJ.user.js

[Feature Request] Debug mode 使用dev 分支

---

.github/workflows/PRAutoclose.yml

Don't delete branches automatically

---

Update.json
XMOJ.user.js

[Feature Request] 修复XMOJ导出AC代码的问题

---

Server/Source/Process.ts
Update.json
XMOJ.user.js

[Bug] 无法读取短消息

---

Update.json
XMOJ.user.js

see https://www.virtualbox.org/

fix name formatting

---

Update.json
XMOJ.user.js

[Feature Request] add username colors everywhere

---

Update.json
XMOJ.user.js

[Bug] 深色模式下 ceinfo.php 代码框仍为白色

---

Update.json
XMOJ.user.js

[Feature Request] 在提醒中加上用户名颜色和badge

---

Server/Source/index.ts
Server/wrangler.toml
Update.json
XMOJ.user.js

[Feature Request] 短消息7天后自动销毁

---

Server/Source/Initial.sql
Server/Source/Process.ts
Update.json
XMOJ.user.js

[Feature Request] 讨论多人回复只提醒一次 || [Feature Request] Discussion multi-person reply only reminds once

---

Update.json
XMOJ.user.js
index.html

修复URL中的问题 || Fix bug in URL

---

Update.json
XMOJ.user.js

fix the "MailPopup" #300

---

Update.json
XMOJ.user.js

[Feature Request] 发帖前提供预览

---

Update.json
XMOJ.user.js

修复无法显示提交代码框

---

XMOJ.user.js

Reverts langningchen/XMOJ-Script#368

Revert "test"

---

.github/workflows/Prerelease.yml
.github/workflows/Release.yml

[Bug] Prerelease 炸了

---

Update.json
XMOJ.user.js

[Bug] 编辑时有时候自动跳掉

---

Update.json
XMOJ.user.js

修复比赛状态页无法上传标程

---

Update.json
XMOJ.user.js

使用异步加载用户名，增快加载速度

---

.github/workflows/AutoLabel.yml
Update/AutoLabel.js

[Feature Request] 自动删除标签

---

Update.json
XMOJ.user.js

解决编辑时出现多余的HTML标签

---

404.html

add 404.html

---

Update/AutoLabel.js
Update/UpdateVersion.js
sitemap-live/0.xml
sitemap.xml

[Feature Request] Make updateversion `git pull` before pushing

---

Server/Source/Process.ts

[Bug] server炸了

---

Server/Source/Process.ts

hash phpsessid

---

Server/Source/Process.ts

[Bug] @渲染出错

---

Server/Source/Initial.sql
Server/Source/Process.ts
Update.json
XMOJ.user.js

更改最后编辑日期的显示方式

---

Update.json
XMOJ.user.js

更换预编译接口加快预编译速度

---

.github/workflows/UpdateToRelease.yml

[Feature Request]当没有修改userscript时允许pr到master

---

Update.json
XMOJ.user.js

解决无法在题目板块发布讨论

---

Update.json
XMOJ.user.js

修复月赛界面下部缺失

---

Update.json
XMOJ.user.js

更换预编译接口，解决奇怪的Compile Error

---

Update.json
XMOJ.user.js

修复关闭`将网站中所有“小明”和“我”关键字替换为...`时左上角仍显示为高老师的OJ

---

Update.json
XMOJ.user.js

修复题目中表格线条缺失
